SET(GMSH_INCLUDE_SEARCH_PATH
    $ENV{HOME}/pkg/gmsh-4.8.4-source/MY_GMSH/include
)

SET(GMSH_LIBRARY_SEARCH_PATH
    $ENV{HOME}/pkg/gmsh-4.8.4-source/MY_GMSH/lib
)

FIND_PATH(GMSH_H    gmsh.h    ${GMSH_INCLUDE_SEARCH_PATH})
FIND_LIBRARY(GMSH_L    NAMES gmsh    PATHS ${GMSH_LIBRARY_SEARCH_PATH})

SET(GMSH_FOUND 1)

FOREACH(var GMSH_H GMSH_L)
    IF(NOT ${var})
    SET(GMSH_FOUND 0)
    ENDIF(NOT ${var})
ENDFOREACH(var)

IF(GMSH_FOUND)
  SET(GMSH_INCLUDE_DIR  ${GMSH_H})
  SET(GMSH_LIBRARIES    ${GMSH_L})
ENDIF(GMSH_FOUND)