SET(EIGEN_INCLUDE_SEARCH_PATH
  $ENV{HOME}/pkg)

FIND_PATH(EIGEN_DENSE Eigen ${EIGEN_INCLUDE_SEARCH_PATH})

SET(EIGEN_FOUND 1)
FOREACH(var EIGEN_DENSE)
  IF(NOT ${var})
	SET(EIGEN_FOUND 0)
  ENDIF(NOT ${var})
ENDFOREACH(var)

IF(EIGEN_FOUND)
	SET(EIGEN_INCLUDE_DIRS  ${EIGEN_DENSE})
ENDIF(EIGEN_FOUND)
