#!/bin/bash

#SBATCH -o job_yin_%j.out

#SBATCH -p torres-gpu #### node name

#SBATCH --qos=normal

#SBATCH -J YINjob

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=4

#SBATCH --cpus-per-task=1

#SBATCH --mem=70G

#SBATCH -q gpu

#SBATCH --gres=gpu:1

# sleep 30

# source ~/.bashrc
# module load cuda/12.0
# for i in {2..4}
# do
#     bash run.sh $i > log_set$(printf "%05d" "$i").txt 2>&1 &
# done
# wait
# python3 Parallel_runSH.py

echo "running ./Parallel_runCommand"
./Parallel_runCommand 2 10 2
